# Generated by Django 5.2.16 on 2026-08-25 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('pacing', models.IntegerField()),
                ('reaction_to_sight', models.IntegerField()),
                ('reaction_to_call', models.IntegerField()),
                ('night_behavior', models.IntegerField()),
                ('activity_level', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('appetite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pets.pet')),
            ],
            options={
                'unique_together': {('pet', 'target_date')},
            },
        ),
    ]
